# Introduction to Scientific Python 

## Numpy

Numpy is imported and aliased to np by convention

In [1]:
import numpy as np

### Array creation

The basic data structure provided by Numpy is the ndarray (n-dimensional array). Each array can store items of the same datatype (e.g. integers, floats, etc.).
Arrays can be created in a number of ways:

- from a python iterable (usually a list)

In [2]:
a = np.array([0, 1, 2]) # a rank 1 array of integers

- using arange (similar to Python's builtin range but returns an array):

In [7]:
a = np.arange(start=0., stop=1., step=.1) # a rank 1 array of floats 
                                          # note that start is included but stop is not
b = np.arange(10) # a rank 1 array of ints from 0 to 9

- using linspace and logspace

In [12]:
a = np.linspace(start=0, stop=5, num=10) # a rank 1 array of 10 evenly-spaced floats between 0 and 5
                                         # this can be thought of as a linear axis of a graph with evenly-spaced ticks
b = np.logspace(-6, -1, 6) # same as above but on logarithmic scale

### Array indexing and shapes

Basic array indexing is similar to Python lists. However, arrays can be indexed along multiple dimensions.

In [16]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(a[0])    # prints [0, 1, 2]
print(a[0, 0]) # prints 0
print(a[:, 1]) # prints [1, 4, 7]

[0 1 2]
0
[1 4 7]


Here : denotes all elements along the axis. For a 2D array (i.e. a matrix) axis 0 is along rows and axis 1 along columns.

Arrays support slicing along each axis, which works very similarly to Python lists.

In [31]:
a = np.linspace(0, 9, 10)
print(a[0:5]) # prints [0., 1., 2., 3., 4.]
b = np.array([[0,  1,  2],
              [3,  4,  5],
              [6,  7,  8],
              [9, 10, 11]])
print(b[:, 0:2]) # prints [[0,  1]
                 #         [3,  4]
                 #         [6,  7]
                 #         [9, 10]]

[ 0.  1.  2.  3.  4.]
[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]


The shape of the array is a tuple of size ```(array.ndim)```, where each element is the size of the array along that axis.

In [17]:
a = np.array([0, 1, 2])
print(a.shape) # prints 3
b = np.array([[[0], [1], [2]],
              [[3], [4], [5]],
              [[6], [7], [8]]])
print(b.shape) # prints (3, 3, 1)

(3,)
(3, 3, 1)


The shape of the array can be changed using the reshape method.

In [24]:
a = np.arange(9).reshape((3, 3))
print(a) # prints [[0 1 2]
         #         [3 4 5]
         #         [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Note that the total number of elements in the new array has to be equal to the number of elements in the initial array. The code below will throw an error.

In [26]:
try:
    a = np.arange(5).reshape((3, 3))
except ValueError as e:
    print(e)

cannot reshape array of size 5 into shape (3,3)


### Mathematical operations and broadcasting

Numpy arrays support the standard mathematical operations.

In [32]:
a = np.arange(9).reshape(3, 3)
b = np.array([10, 11, 12])
print(a + 1) # operation is performed on the whole array
print(a - 5)
print(b * 3)
print(b / 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
[30 33 36]
[ 5.   5.5  6. ]


Operations involving 2 or more arrays are also possible. However, they must obey the rules of broadcasting.

In [37]:
print(a * a) # multiply each element of a by itself
print(a + b) # add b elementwise to every row of a
print(a[:, 0] + b) # add b only to the first column of a

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[10 12 14]
 [13 15 17]
 [16 18 20]]
[10 14 18]
