# Introduction to Numpy

*Exercise difficulty rating:*  
*[1]* easy. ~1 min  
*[2]* medium. ~2-3 minutes  
*[3]* difficult. Suitable for a standalone project. 

## Numpy

Numpy is imported and aliased to np by convention

In [2]:
import numpy as np

### Array creation

The basic data structure provided by Numpy is the ndarray (n-dimensional array). Each array can store items of the same datatype (e.g. integers, floats, etc.).
Arrays can be created in a number of ways:

- from a Python iterable (usually a list)

In [2]:
a = np.array([0, 1, 2]) # a rank 1 array of integers

- using arange (similar to Python's builtin range but returns an array):

In [3]:
a = np.arange(start=0., stop=1., step=.1) # a rank 1 array of floats 
                                          # note that start is included but stop is not
b = np.arange(10) # a rank 1 array of ints from 0 to 9

- using linspace and logspace

In [4]:
a = np.linspace(start=0, stop=5, num=10) # a rank 1 array of 10 evenly-spaced floats between 0 and 5
                                         # this can be thought of as a linear axis of a graph with evenly-spaced ticks
b = np.logspace(-6, -1, 6) # same as above but on logarithmic scale

- using built-in helper functions

In [47]:
zeros = np.zeros(5) # rank 1 array of 5 zeros
ones = np.ones(3)   # it's in the name
eye = np.eye(8) # 8x8 identity matrix

### Exercises

- create a set of axes for a graph as Numpy arrays. Let the x axis be **uniformly spaced** from 0 to 60 with scale 1 (i.e. one tick per value) and the y axis be on **log scale** and represent the powers of 10 from 0 to 6 *[1]*.

In [30]:
# answer:
x = np.linspace(0, 60, 61)
y = np.logspace(0, 6, 7)

### Array indexing and shapes

Basic array indexing is similar to Python lists. However, arrays can be indexed along multiple dimensions.

In [103]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(a[0])    # prints [0, 1, 2]
print(a[0, 0]) # prints 0
print(a[:, 1]) # prints [1, 4, 7]

[0 1 2]
0
[1 4 7]


Here : denotes all elements along the axis. For a 2D array (i.e. a matrix) axis 0 is along rows and axis 1 along columns.

#### Slicing
Arrays support slicing along each axis, which works very similarly to Python lists.

In [100]:
a = np.linspace(0, 9, 10)
print(a[0:5]) # prints [0., 1., 2., 3., 4.]
b = np.array([[0,  1,  2],
              [3,  4,  5],
              [6,  7,  8],
              [9, 10, 11]])
print('-'*12)
print(b[:, 0:2]) # prints [[0,  1]
                 #         [3,  4]
                 #         [6,  7]
                 #         [9, 10]]

[ 0.  1.  2.  3.  4.]
------------
[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]


#### Boolean indexing
Arrays can also be indexed using boolean values

In [13]:
a = np.arange(10)
print(a[a < 5]) # prints [0, 1, 2, 3, 4]
print(a[a % 2 == 0]) # prints [0, 2, 4, 6, 8]

[0 1 2 3 4]
[0 2 4 6 8]


#### Shapes
The shape of the array is a tuple of size ```(array.ndim)```, where each element is the size of the array along that axis.

In [8]:
a = np.array([0, 1, 2])
print(a.shape) # prints 3
b = np.array([[[0], [1], [2]],
              [[3], [4], [5]],
              [[6], [7], [8]]])
print(b.shape) # prints (3, 3, 1)

(3,)
(3, 3, 1)


The shape of the array can be changed using the reshape method.

In [9]:
a = np.arange(9).reshape((3, 3))
print(a) # prints [[0 1 2]
         #         [3 4 5]
         #         [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Note that the total number of elements in the new array has to be equal to the number of elements in the initial array. The code below will throw an error.

In [10]:
try:
    a = np.arange(5).reshape((3, 3))
except ValueError as e:
    print(e)

cannot reshape array of size 5 into shape (3,3)


### Exercises

- get the **first column** and the **third row** of the following array *[1]*.

In [37]:
a = np.array([[23, 324,  21, 116], 
              [ 0,  55, 232, 122],
              [42,  43,  44,  45],
              [178, 67, 567,  55]])

In [ ]:
# answer
first_column = a[:, 0] 
third_row = a[2]

- find all numbers divisible by 7 between 0 and 50 *[1]*.

In [39]:
# answer
a = np.arange(0, 51)
divisible_by_7 = a[a % 7 == 0]

### Mathematical operations and broadcasting

#### Basic arithmetics
Numpy arrays support the standard mathematical operations.

In [20]:
a = np.arange(9).reshape(3, 3)
b = np.array([10, 11, 12])
print(a + 1) # operation is performed on the whole array
print('-'*12)
print(a - 5)
print('-'*12)
print(b * 3)
print('-'*12)
print(b / 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------
[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
------------
[30 33 36]
------------
[ 5.   5.5  6. ]


#### Broadcasting
Operations involving 2 or more arrays are also possible. However, they must obey the rules of broadcasting.

In [19]:
print(a * a) # multiply each element of a by itself
print('-'*12)
print(a + b) # add b elementwise to every row of a
print('-'*12)
print(a[:, 0] + b) # add b only to the first column of a

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
------------
[[10 12 14]
 [13 15 17]
 [16 18 20]]
------------
[10 14 18]


Notice that in the last 2 examples above we could perform the operations even though the arrays did not have the same shape. This is one of the most powerful features of Numpy that allows for very efficient computations. You can read more about broadcasting [in the official documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) and [here](http://cs231n.github.io/python-numpy-tutorial/#numpy-broadcasting).

#### Built-in functions
Numpy has efficient implementations of many standard mathematical and statistical functions.

In [84]:
a = np.random.normal(0, 1, (4, 3)) # np.random.normal creates an array of normally-distributed random numbers
                                   # with given mean and standard deviation (e.g. 0 and 1) and in given shape.
print(np.mean(a)) # a number close to 0
print('-'*12)
print(np.mean(a) == a.mean()) # many functions are also implemented as methods in the ndarray class
print('-'*12)
print(np.std(a)) # close to 1
print('-'*12)
print(np.sum(a))  # Compute sum of all elements
print('-'*12)
print(np.sum(a, axis=0))  # Compute sum of each column
print('-'*12)
print(np.sum(a, axis=1))  # Compute sum of each row

0.234072030508
------------
True
------------
0.642666136464
------------
2.80886436609
------------
[ 0.44603017  0.60719111  1.75564308]
------------
[ 2.93429278 -1.5653583   0.28745882  1.15247107]


### Exercises

- create a **6x6 array** of normally distributed random numbers with **mean 5** and **standard deviation 10**. Print its computed mean and standard deviation *[1]*.

In [52]:
# answer
a = np.random.normal(5, 10, (6, 6))
print(np.mean(a))
print(a.std())

5.09409892265
8.87640405235


- add 5 to every element of the array from the previous exercise *[1]*.

In [53]:
# answer
a += 5

- multiply the **third column** of the array from the previous exercise by the given array *[1]*.

In [54]:
b = np.array([0, 1, 0, 1, 0, 1])

In [55]:
# answer
a[:, 2] *= b

- create a 7x7 matrix with 7 on the leading diagonal and 0 everywhere else (**note**: you might find the ```eye``` function useful) *[1]*.

In [56]:
# answer
a = np.eye(7) * 7

- the following array represents the spending, in pounds of 4 people over 5 months (rows represent time and columns the individuals).
  Compute the **total spending of person 2**. Compute the **average spending in each month for each person** (**note**: use the ```axis``` argument) *[1]*.

In [146]:
#            person     1        2       3        4      # month
spending = np.array([[450.55, 340.67, 1023.98, 765.30],  # 1
                     [430.46, 315.99,  998.48, 760.78],  # 2
                     [470.30, 320.34, 1013.67, 774.50],  # 3
                     [445.62, 400.60, 1020.20, 799.45],  # 4
                     [432.01, 330.13, 1011.76, 750.91]]) # 5

In [147]:
# answer
total_person_2 = np.sum(spending[:, 1])
mean_all = np.mean(spending, axis=0)

- the *outer product* of two vectors ```u``` and ```v``` can be obtained by multiplying each element of ```u``` by each element of ```v```. Compute the outer product of the given vectors (**note**: use the ```reshape``` function) *[2]*.

In [57]:
v = np.array([1,2,3])
w = np.array([4,5])

In [51]:
# answer
outer = np.reshape(v, (3, 1)) * w

[[ 4  5]
 [ 8 10]
 [12 15]]


### Linear algebra

Numpy has extensive support for linear algebra operations.

In [123]:
u = np.array([4, 2, 5]) # a row vector in R^3, shape (3,)
v = np.array([.5, .3, .87])
a = np.array([[3, -2,  1],
              [9,  6, 10],
              [6, -4,  3]]) # a 3x3 matrix
b = np.array([[.25,  .2],
              [4.3,  .1],
              [ 1., .82]]) # a 3x2 matrix

print(u.dot(v)) # the dot product of vectors
print('-'*12)

print(a.dot(u)) # the matrix vector product
print('-'*12)

print(a.dot(b)) # matrix multiplication
print('-'*12)

print(np.linalg.norm(u)) # norm aka magnitude of a vector
print('-'*12)

print(np.outer(u, v)) # uv^T
print('-'*12)

print(np.transpose(b)) # equivalent to b.T
print('-'*12)

print(u.T) # note that this does not turn a row vector into column vector
           # i.e. the shape of u.T is still (3,)
print('-'*12)

print(np.linalg.inv(a)) # find the inverse of a matrix, a^-1
print('-'*12)

print(np.linalg.solve(a, u)) # solve the linear system ax = u for x

6.95
------------
[13 98 31]
------------
[[ -6.85   1.22]
 [ 38.05  10.6 ]
 [-12.7    3.26]]
------------
6.7082039325
------------
[[ 2.    1.2   3.48]
 [ 1.    0.6   1.74]
 [ 2.5   1.5   4.35]]
------------
[[ 0.25  4.3   1.  ]
 [ 0.2   0.1   0.82]]
------------
[4 2 5]
------------
[[ 1.61111111  0.05555556 -0.72222222]
 [ 0.91666667  0.08333333 -0.58333333]
 [-2.         -0.          1.        ]]
------------
[ 2.94444444  0.91666667 -3.        ]


### Exercises

- write a function to compute the Euclidean distance between two vectors. Evaluate it on the given data *[1]*.

In [227]:
u = np.array([.4, .23, .01])
v = np.array([.12, 1.1, .5])

In [234]:
# answer
def dist(u, v):
    return np.sqrt(np.sum((u - v) ** 2))

# or
def dist(u, v):
    return np.linalg.norm(u - v)

- the closed-form solution for the linear regression problem can be written as  
  
 $W = (X^{T}X)^{-1}X^{T}y$  
   
 Compute the weight matrix $W$ for the given data. Check if your weight and bias are close to the true values (2, 5). Compute the estimated values $\hat{y}$ for the test dataset *[2]*.

In [36]:
def f_true(x):
    return 2 * x + 5

def f(x):
    return f_true(x) + np.random.normal(0, 1, xx.shape[0])

xx = np.linspace(-10, 10)
X = np.ones((xx.shape[0], 2))
X[:, 1] = xx
y = f(xx)
test = np.array([-5.5, 1.2, 4.8, 9.])

In [45]:
# answer
W = (np.linalg.inv(X.T.dot(X)).dot(X.T)).dot(y)

# or
W = np.linalg.pinv(X).dot(y)

y_hat = test * W[1] + W[0]

### Vectorized functions and speed

The functions in Numpy, including the mathematical operators are implemented in efficient C code operating on whole arrays. Therfore, it is usually a good idea to avoid element-by-element computations in a ```for``` or ```while``` loop. Functions that operate on whole arrays are referred to as *vectorized*.

In [193]:
# a non-vectorized function
def log_pos_p1(x):
    
    """Compute the natural log + 1 of positive elements in x. 
       Return 0 for elements < 0."""
    
    result = np.zeros_like(x) # create an array of zeros with the same shape and type as x
    for i, e in np.ndenumerate(x): # ndenumerate returns tuples (index, element)
        if e > 0:
            result[i] = np.log(e) + 1
    return result
            
def log_pos_p1_vectorized(x):
    # same as above but faster
    result = np.zeros_like(x)
    result[x > 0] = np.log(x[x > 0]) + 1
    return result

In [194]:
x = np.arange(-1000., 1000.)

In [200]:
%timeit result_slow = log_pos_p1(x)

2.62 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [199]:
%timeit result_vectorized = log_pos_p1_vectorized(x)

21.1 µs ± 990 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [201]:
# check if the results are correct
np.allclose(result_slow, result_vectorized)

True

### Exercises

- the *rectified linear unit* (aka ReLU) is a commonly used activation function in machine learning. It can be computed using the following Python function:
  ```python
     def relu(x):
        result = np.zeros_like(x) # create an array of 0s with the same shape and type as x
        for i, e in np.ndenumerate(x): # ndenumerate returns tuples (index, element)
            if x > 0:
                result[i] = e
        return result
  ```
  Vectorize this function. Evaluate the running time using the ```%timeit``` command on the data below *[2]*.

In [206]:
def relu(x):
    result = np.zeros_like(x) # create an array of 0s with the same shape and type as x
    for i, e in np.ndenumerate(x): # ndenumerate returns tuples (index, element)
        if e > 0:
            result[i] = e
    return result

x = np.arange(-10000., 10000.)

In [38]:
# answer
def relu_vectorized(x):
    result = np.zeros_like(x)
    result[x > 0] = x[x > 0]
    return result

# or
def relu_vectorized(x):
    return np.where(x > 0, x, 0) # np.where returns elements from the first array if condition is true,
                                 # second otherwise

- the integral of a function can be numerically aproximated using the *trapezoidal rule*, defined as:  
  $\displaystyle\int_{a}^{b}f(x)dx \approx \frac{h}{2}f(a) + \frac{h}{2}f(b) + h\displaystyle\sum_{i=1}^{n-1}f(a + ih), \space h = \frac{b - a}{n}$  
  Write a vectorized function to integrate a function using the trapezoidal rule. It should accept as arguments the function to integrate, the lower and upper bounds and the number of iterations $n$. **Do not** use an explicit ```for```-loop for the summation. Use your function to intergrate $x^3$ from 0 to 1 using $n=1000$ (the true value of this integral is $\frac{1}{4}$) *[2]*.

In [218]:
def f(x):
    return x ** 3

a = 0
b = 1
n = 1000

In [219]:
# answer
def trapz(f, a, b, n):
    h = (b - a) / n
    x = np.linspace(1., n-1, n)
    return (h/2) * f(a) + (h/2) * f(b) + h * np.sum(f(a + x * h))

## Challenges

- Write a simple gradient descent optimizer using numpy *[3]*. Use it to fit a linear regression model to the sample data from the previous exercises *[2]*. You might find the notebook from the first workshop on linear models useful.

- Write a function to compute the elements of the Mandelbrot set with given resolution *[3]*. Estimate the area of the computed set *[2]*. Make the function as fast as possible using vectorization *[3]*.

- *Logistic regression* is a popular model used to estimate the probability of a binary outcome (i.e. 0 or 1). It belongs to a broader class of *generalized linear models*. Write a logistic regression solver using Numpy *[3]*. You can adopt multiple approaches, e.g. gradient descent from the first challenge or algorithms like *Newton's method* or *iteratively-reweighted least squares* ([Wikipedia](https://en.wikipedia.org/wiki/Logistic_regression) is a good place to start). Test your implementation on the [classic Titanic dataset](https://www.kaggle.com/c/titanic) or any other binary classification problem. Compare the performance of your model to a standard implementation (e.g. [scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)) using a metric of your choice. Compare the speed of your method to the reference implementation and try to make it as fast as possible (using vectorization, faster algorithms, etc.)